name: colorize
version: 0.0.1
author: Matthew Butler <butler.matthew@gmail.com>
description: The Colorize library provides a Dart-based input type="color" Polyfill and a custom element color picker. Based on the original dart-color-picker by code respawn
homepage: https://github.com/butlermatt/colorize
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  browser: any
  polymer: '>=0.9.0 <0.10.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.10.0'
